"""
Ashby Job Spider - Extracts job details from Ashby HQ job portal.

Author: Senior Data Engineer
Course: Tools & Techniques for DS - University of Central Punjab
Date: March 2026

This spider reads job URLs from CSV and extracts structured job data
with 9 required fields: job title, company name, location, department,
employment type, posted date, job URL, description, and required skills.
"""

import scrapy
import csv
import logging
from datetime import datetime
from scrapy.loader import ItemLoader
from ..items import JobItem


class AshbyJobSpider(scrapy.Spider):
    """
    Spider for extracting job details from Ashby HQ portal.
    
    Attributes:
        name (str): Spider identifier
        allowed_domains (list): Allowed domains for scraping
        start_urls (list): URLs to start scraping from
    """
    
    name = 'ashby_jobs'
    allowed_domains = ['jobs.ashbyhq.com']
    
    def __init__(self, *args, **kwargs):
        """Initialize spider with job URLs from CSV."""
        super(AshbyJobSpider, self).__init__(*args, **kwargs)
        self.job_urls = []
        self.load_job_urls_from_csv()
    
    def load_job_urls_from_csv(self, csv_path='../data/raw/job_links.csv'):
        """
        Load job URLs from CSV file generated by Selenium scraper.
        
        Args:
            csv_path (str): Path to CSV file with job URLs
        """
        try:
            with open(csv_path, 'r', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    url = row.get('job_url', '').strip()
                    if url:
                        self.job_urls.append(url)
            
            self.logger.info(f"Loaded {len(self.job_urls)} job URLs from CSV")
        
        except FileNotFoundError:
            self.logger.error(f"CSV file not found: {csv_path}")
            self.job_urls = []
        except Exception as e:
            self.logger.error(f"Error loading job URLs from CSV: {e}")
            self.job_urls = []
    
    def start_requests(self):
        """
        Generate requests for all job URLs.
        
        Yields:
            Scrapy Request objects
        """
        for url in self.job_urls:
            yield scrapy.Request(
                url=url,
                callback=self.parse,
                meta={'dont_obey_robotstxt': False},
                dont_filter=True
            )
    
    def parse(self, response):
        """
        Parse job detail page and extract required fields from embedded JSON.
        
        Args:
            response: Scrapy response object
            
        Yields:
            JobItem objects with extracted data
        """
        loader = ItemLoader(item=JobItem(), response=response)
        
        try:
            # Ashby job pages are SPAs, the data is embedded as JSON in window.__appdata
            # Look through all script tags to find the one with appdata
            scripts = response.xpath('//script/text()').getall()
            script_text = None
            for script in scripts:
                if '__appdata' in script.lower():
                    script_text = script
                    break
            
            if not script_text:
                self.logger.warning(f"Could not find window.__appdata script on {response.url}")
                # Log a bit of the page to see what's going on
                self.logger.warning(f"Page title: {response.xpath('//title/text()').get()}")
                return
                
            # Extract JSON substring
            import json
            import re
            
            # Use case-insensitive match for __appdata
            json_match = re.search(r'window\.__appdata = ({.*});\s*fetch', script_text, re.IGNORECASE | re.DOTALL)
            
            # If fetch is missing, just try to grab the JSON
            if not json_match:
                json_match = re.search(r'window\.__appdata = ({.*});', script_text, re.IGNORECASE | re.DOTALL)
            
            if not json_match:
                self.logger.warning(f"Could not parse window.__appdata JSON from {response.url}")
                return
                
            try:
                appdata = json.loads(json_match.group(1))
            except json.JSONDecodeError as e:
                self.logger.error(f"Failed to decode JSON from {response.url}: {e}")
                return
                
            # Extract basic info
            organization = appdata.get('organization', {})
            posting = appdata.get('posting', {})
            
            item = JobItem()
            
            # 1. Extract Job Title
            item['job_title'] = posting.get('title', '').strip()
            
            # 2. Extract Company Name
            company_name = organization.get('name', '').capitalize()
            if not company_name:
                company_name = 'Ashby Demo Org'
            item['company_name'] = company_name.strip()
            
            # 3. Extract Location
            location_name = posting.get('locationName', '') or posting.get('locationExternalName', '') or 'Not specified'
            workplace_type = posting.get('workplaceType', '')
            item['location'] = self._tag_location_type(location_name, workplace_type)
            
            # 4. Extract Department
            department = posting.get('departmentName', '') or posting.get('departmentExternalName', '') or 'General'
            item['department'] = department.strip()
            
            # 5. Extract Employment Type
            employment_type = posting.get('employmentType', '') 
            if employment_type:
                employment_type = employment_type.replace('_', '-').title()
            else:
                employment_type = 'Full-time'
            item['employment_type'] = employment_type.strip()
            
            # 6. Extract Posted Date
            posted_date = posting.get('publishedDate', '') or posting.get('updatedAt', '')[:10] or 'Recently'
            item['posted_date'] = posted_date.strip()
            
            # 7. Add Job URL
            item['job_url'] = response.url
            
            # 8. Extract Job Description
            description_text = posting.get('descriptionPlainText', '') 
            if not description_text:
                desc_parts = posting.get('descriptionParts', {})
                html_body = desc_parts.get('descriptionBody', {}).get('plain', '')
                description_text = html_body
            item['job_description'] = description_text
            
            # 9. Extract Required Skills from plain text description
            skills = self._extract_skills(description_text)
            item['required_skills'] = skills
            
            # Add extraction timestamp and source
            item['extracted_timestamp'] = datetime.now().isoformat()
            item['source'] = 'ashby'
            
            if self._validate_item(item):
                self.logger.info(f"Extracted job: {item.get('job_title')}")
                yield item
            else:
                self.logger.warning(f"Incomplete job data from: {response.url}")
        
        except Exception as e:
            self.logger.error(f"Error parsing job page {response.url}: {e}")
            import traceback
            self.logger.error(traceback.format_exc())
    
    def _tag_location_type(self, location_text, workplace_type=""):
        """
        Add remote/hybrid/on-site tag to location.
        """
        location_lower = str(location_text).lower()
        workplace_lower = str(workplace_type).lower()
        
        # Check explicit workplace type first
        if 'remote' in workplace_lower or 'telecommute' in workplace_lower:
            tag = '[REMOTE]'
        elif 'hybrid' in workplace_lower:
            tag = '[HYBRID]'
        elif 'on-site' in workplace_lower or 'onsite' in workplace_lower:
            tag = '[ON-SITE]'
        # Fall back to text parsing if no explicit type
        elif 'remote' in location_lower:
            tag = '[REMOTE]'
        elif 'hybrid' in location_lower:
            tag = '[HYBRID]'
        else:
            tag = '[ON-SITE]'
        
        return f"{location_text} {tag}".strip()
    
    def _extract_skills(self, description_text, max_skills=15):
        """
        Extract required skills from job description text.
        """
        if not description_text:
            return []
            
        skills = []
        try:
            description_lower = description_text.lower()
            
            # We don't have DOM bullet points anymore, so we look for common skills
            common_skills = [
                'Python', 'Java', 'JavaScript', 'C++', 'C#', 'TypeScript',
                'React', 'Angular', 'Vue', 'Django', 'FastAPI', 'Flask',
                'SQL', 'MongoDB', 'PostgreSQL', 'MySQL', 'AWS', 'GCP', 'Azure',
                'Docker', 'Kubernetes', 'Git', 'CI/CD', 'REST API', 'GraphQL',
                'Machine Learning', 'Data Science', 'Deep Learning', 'TensorFlow',
                'Pandas', 'NumPy', 'Scikit-learn', 'Excel', 'Tableau', 'Power BI',
                'Fintech', 'Payments', 'Cross-border', 'Treasury', 'Stablecoin', 'Web3'
            ]
            
            for skill in common_skills:
                # Use word boundaries to not match 'java' in 'javascript'
                import re
                if re.search(rf'\b{re.escape(skill.lower())}\b', description_lower):
                    skills.append(skill)
            
            self.logger.debug(f"Extracted {len(skills)} skills")
            return skills[:max_skills]
        
        except Exception as e:
            self.logger.warning(f"Error extracting skills: {e}")
            return skills
    
    def _validate_item(self, item):
        """
        Validate that item has minimum required fields.
        """
        required_fields = ['job_title', 'job_url']
        
        for field in required_fields:
            if not item.get(field):
                return False
        
        return True
