"""
Ashby Job Spider - Extracts job details from Ashby HQ job portal.

Author: Senior Data Engineer
Course: Tools & Techniques for DS - University of Central Punjab
Date: March 2026

This spider reads job URLs from CSV and extracts structured job data
with 9 required fields: job title, company name, location, department,
employment type, posted date, job URL, description, and required skills.
"""

import scrapy
import csv
import logging
from datetime import datetime
from scrapy.loader import ItemLoader
from scrapy.loader.processors import TakeFirst, MapCompose, Join
from ..items import JobItem


class AshbyJobSpider(scrapy.Spider):
    """
    Spider for extracting job details from Ashby HQ portal.
    
    Attributes:
        name (str): Spider identifier
        allowed_domains (list): Allowed domains for scraping
        start_urls (list): URLs to start scraping from
    """
    
    name = 'ashby_jobs'
    allowed_domains = ['jobs.ashbyhq.com']
    
    def __init__(self, *args, **kwargs):
        """Initialize spider with job URLs from CSV."""
        super(AshbyJobSpider, self).__init__(*args, **kwargs)
        self.logger = logging.getLogger(__name__)
        self.job_urls = []
        self.load_job_urls_from_csv()
    
    def load_job_urls_from_csv(self, csv_path='../../data/raw/job_links.csv'):
        """
        Load job URLs from CSV file generated by Selenium scraper.
        
        Args:
            csv_path (str): Path to CSV file with job URLs
        """
        try:
            with open(csv_path, 'r', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    url = row.get('job_url', '').strip()
                    if url:
                        self.job_urls.append(url)
            
            self.logger.info(f"Loaded {len(self.job_urls)} job URLs from CSV")
        
        except FileNotFoundError:
            self.logger.error(f"CSV file not found: {csv_path}")
            self.job_urls = []
        except Exception as e:
            self.logger.error(f"Error loading job URLs from CSV: {e}")
            self.job_urls = []
    
    def start_requests(self):
        """
        Generate requests for all job URLs.
        
        Yields:
            Scrapy Request objects
        """
        for url in self.job_urls:
            yield scrapy.Request(
                url=url,
                callback=self.parse,
                meta={'dont_obey_robotstxt': False},
                dont_filter=True
            )
    
    def parse(self, response):
        """
        Parse job detail page and extract required fields.
        
        Args:
            response: Scrapy response object
            
        Yields:
            JobItem objects with extracted data
        """
        loader = ItemLoader(item=JobItem(), response=response)
        
        try:
            # 1. Extract Job Title
            job_title = response.css('h1::text').get() or \
                       response.xpath('//h1//text()').get() or \
                       response.css('[data-testid="job-title"]::text').get() or ''
            
            loader.add_value('job_title', job_title.strip())
            
            # 2. Extract Company Name
            company_name = response.css('h2::text').get() or \
                          response.xpath('//a[contains(@href, "ashby")]/text()').get() or \
                          'Ashby Demo Org'  # Default from URL structure
            
            loader.add_value('company_name', company_name.strip())
            
            # 3. Extract Location (with remote/hybrid tag detection)
            location_text = response.css('[class*="location"]::text').get() or \
                           response.xpath('//text()[contains(., "Remote") or contains(., "Hybrid") or contains(., "On-site")]').get() or \
                           'Not specified'
            
            # Tag remote/hybrid status
            location_tag = self._tag_location_type(location_text)
            loader.add_value('location', location_tag)
            
            # 4. Extract Department
            department = response.css('[class*="department"]::text').get() or \
                        response.xpath('//strong[contains(text(), "Department")]/following-sibling::text()').get() or \
                        response.xpath('//dt[contains(text(), "Department")]/following-sibling::dd/text()').get() or \
                        'General'
            
            loader.add_value('department', department.strip())
            
            # 5. Extract Employment Type
            employment_type = response.css('[class*="employment"]::text').get() or \
                             response.xpath('//text()[contains(., "Full-time") or contains(., "Part-time") or contains(., "Contract") or contains(., "Intern")]').get() or \
                             'Full-time'
            
            loader.add_value('employment_type', employment_type.strip())
            
            # 6. Extract Posted Date
            posted_date = response.css('[class*="date"]::text').get() or \
                         response.xpath('//text()[contains(., "Posted") or contains(., "2025") or contains(., "2026")]').get() or \
                         'Recently'
            
            loader.add_value('posted_date', posted_date.strip())
            
            # 7. Add Job URL
            loader.add_value('job_url', response.url)
            
            # 8. Extract Job Description
            # Combine all description text
            description_parts = response.css('[class*="description"]::text').getall() or \
                               response.xpath('//div[@class="job-description"]//text()').getall() or \
                               response.css('main::text').getall() or \
                               []
            
            job_description = ' '.join([text.strip() for text in description_parts if text.strip()])
            loader.add_value('job_description', job_description)
            
            # 9. Extract Required Skills from bullet points
            skills = self._extract_skills(response)
            loader.add_value('required_skills', '|'.join(skills))
            
            # Add extraction timestamp
            loader.add_value('extracted_timestamp', datetime.now().isoformat())
            
            item = loader.load_item()
            
            # Validate item before yielding
            if self._validate_item(item):
                self.logger.info(f"Extracted job: {item.get('job_title')}")
                yield item
            else:
                self.logger.warning(f"Incomplete job data from: {response.url}")
        
        except Exception as e:
            self.logger.error(f"Error parsing job page {response.url}: {e}")
    
    def _tag_location_type(self, location_text):
        """
        Add remote/hybrid/on-site tag to location.
        
        Args:
            location_text (str): Location text to tag
            
        Returns:
            str: Tagged location string
        """
        location_text = str(location_text).lower()
        
        if 'remote' in location_text:
            tag = '[REMOTE]'
        elif 'hybrid' in location_text:
            tag = '[HYBRID]'
        else:
            tag = '[ON-SITE]'
        
        return f"{location_text} {tag}"
    
    def _extract_skills(self, response, max_skills=15):
        """
        Extract required skills from job description.
        
        Args:
            response: Scrapy response object
            max_skills (int): Maximum skills to extract
            
        Returns:
            list: List of extracted skills
        """
        skills = []
        
        try:
            # Method 1: Look for bullet points with skills
            skill_items = response.css('li::text').getall() or \
                         response.xpath('//ul/li/text()').getall() or \
                         []
            
            for item in skill_items[:max_skills]:
                skill = item.strip()
                # Filter out very short items (likely not skills)
                if len(skill) > 3 and len(skill) < 100:
                    skills.append(skill)
            
            # Method 2: Extract from common skill patterns
            if not skills:
                description = response.css('[class*="description"]::text').getall()
                description_text = ' '.join(description)
                
                common_skills = [
                    'Python', 'Java', 'JavaScript', 'C++', 'C#', 'TypeScript',
                    'React', 'Angular', 'Vue', 'Django', 'FastAPI', 'Flask',
                    'SQL', 'MongoDB', 'PostgreSQL', 'MySQL', 'AWS', 'GCP', 'Azure',
                    'Docker', 'Kubernetes', 'Git', 'CI/CD', 'REST API', 'GraphQL',
                    'Machine Learning', 'Data Science', 'Deep Learning', 'TensorFlow',
                    'Pandas', 'NumPy', 'Scikit-learn', 'Excel', 'Tableau', 'Power BI'
                ]
                
                for skill in common_skills:
                    if skill.lower() in description_text.lower():
                        skills.append(skill)
            
            self.logger.debug(f"Extracted {len(skills)} skills")
            return skills[:max_skills]
        
        except Exception as e:
            self.logger.warning(f"Error extracting skills: {e}")
            return skills
    
    def _validate_item(self, item):
        """
        Validate that item has minimum required fields.
        
        Args:
            item: JobItem to validate
            
        Returns:
            bool: True if valid, False otherwise
        """
        required_fields = ['job_title', 'job_url']
        
        for field in required_fields:
            if not item.get(field):
                return False
        
        return True
